name: grafana
version: 0.0.3
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
sources:
  - https://github.com/grafana/grafana
maintainers:
  - name: Employment Hero
    email: devops@employmentinnovations.com
engine: gotpl
