# Default values for logdna-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: alerta/alerta-web
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

env: []
ingress: {}
updateStrategy: RollingUpdate

